### ISSUE TITLE
authentication/password isn't remembered

### ISSUE THREAD

**Issue by carlaberkers** [canonical/labels#4] opened 2017-07-05 11:08 UTC
I've added the labels to the different repositories that the snappy squad uses, and find that every time I have to add the GitHub token, then it asks me to set a password for next time and I do, then next time it asks me for a token again.

it would be great if this tool remembered the password I set.

other than that tool works great - thanks Will!

**Comment by Caleb-Ellis** [comment] 2017-11-29 10:04
The labels are created using [git-labelmaker](https://github.com/himynameisdave/git-labelmaker) which isn't a tool we own. Also I don't seem to get the problem of having to enter a token each time - only the password (which is by design). Closing as I believe it's not an issue we have control over.

**Closed as completed by Caleb-Ellis** 2017-11-29 10:04 UTC

**Comment by anthonydillon** [comment] 2017-12-01 08:41
@Caleb-Ellis this is a valid bug but on the git-labelmaker project. After talking with @WillMoggridge some time ago. I believe, it is to do with using SSH over https clones.
